#!/usr/bin/python3

from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QUrl
from PySide6.QtGui import QIcon
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtWebEngineQuick import QtWebEngineQuick

import sys
import os
import gettext
gettext.textdomain("epi")
_ = gettext.gettext



from epigtk.Core import Core
import epigtk.IconProvider as IconProvider

c=Core.get_core()

os.environ["QTWEBENGINE_CHROMIUM_FLAGS"]="--no-sandbox"

app = QApplication(sys.argv)
app.setDesktopFileName("epi-gtk")
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
mainStackBridge=c.mainStack
packageStackBridge=c.packageStack
engine.addImageProvider("iconProvider",IconProvider.IconProvider())
context.setContextProperty("mainStackBridge", mainStackBridge)
context.setContextProperty("packageStackBridge",packageStackBridge)

url = QUrl("/usr/lib/python3/dist-packages/epigtk/rsrc/epi-gui.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(app.quit)
ret=app.exec()
del engine
del app
sys.exit(ret)

