#!/usr/bin/python3

from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QUrl
from PySide2.QtGui import QIcon
from PySide2.QtQml import QQmlApplicationEngine

import sys
import os
import gettext
gettext.textdomain("epi")
_ = gettext.gettext



import epigtk.EpiGui as EpiGui
import epigtk.IconProvider as IconProvider

os.environ["QTWEBENGINE_CHROMIUM_FLAGS"]="--no-sandbox"

app = QApplication(sys.argv)
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
epiBridge=EpiGui.EpiGui()
engine.addImageProvider("iconProvider",IconProvider.IconProvider())
context.setContextProperty("epiBridge", epiBridge)

url = QUrl("/usr/lib/python3/dist-packages/epigtk/rsrc/epi-gui.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/epi-gtk.svg"));
ret=app.exec_()
del engine
del app
sys.exit(ret)

